In [2]:
# Importing the Libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [4]:
# Loading the Dataset
data = pd.read_csv('Student Grades Prediction.csv')

In [6]:
# Analyse the Top 5 rows of the Data
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10


##### In this dataset the G1 represents the grades of the first period, G2 represents the grades of the second period, and G3 represents the final grades.

In [11]:
# Now let’s prepare the data and let’s see how we can predict the final grades of the students
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], axis = 1))
y = np.array(data[predict])

In [13]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [15]:
# Now let’s see how to train a linear regression model for the task of student grades prediction
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.7416226507524256


##### The linear regression model gave an accuracy of about 74% which is not bad in this task.

In [20]:
# Now let’s have a look at the predictions made by the students’ grade prediction model
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[10.28370505  6.82568205 11.81478169  8.74451502  6.82568205]
 [10.28370505 10.28370505 11.81478169  8.74451502 16.1231612 ]
 [ 7.8623546   4.98692838 11.81478169 12.67490154  6.39400009]
 ...
 [ 6.39400009  4.98692838 10.77276219 12.67490154 12.67490154]
 [15.35326613  9.17506656 10.77276219  8.74451502  8.74451502]
 [ 4.98692838  9.91647257 10.77276219  8.74451502 10.28370505]] [[[12 10  2  0 14]
  [ 6  8  1  1  0]
  [12 12  3  0  2]
  [ 9  9  1  0  6]
  [ 6  8  1  1  0]]

 [[12 10  2  0 14]
  [12 10  2  0 14]
  [12 12  3  0  2]
  [ 9  9  1  0  6]
  [15 16  3  0  2]]

 [[ 6  9  1  2 14]
  [ 7  6  1  1  0]
  [12 12  3  0  2]
  [11 13  1  1 10]
  [ 7  7  3  0  6]]

 ...

 [[ 7  7  3  0  6]
  [ 7  6  1  1  0]
  [11 11  2  0  2]
  [11 13  1  1 10]
  [11 13  1  1 10]]

 [[16 15  4  0  7]
  [11  9  2  0 14]
  [11 11  2  0  2]
  [ 9  9  1  0  6]
  [ 9  9  1  0  6]]

 [[ 7  6  1  1  0]
  [12 10  2  0  2]
  [11 11  2  0  2]
  [ 9  9  1  0  6]
  [12 10  2  0 14]]] [array([[11,  8, 11, 10,  8]